### ISSUE TITLE
Add Maximum Rate Validation in `create_amm_config`

### ISSUE THREAD

**Issue by OforgeO** [GooseFX1/gamma-swap#35]
The `create_amm_config` function doesn't check for the maximum allowable rates for `trade_fee_rate`, `protocol_fee_rate`, and `fund_fee_rate`. 

The `update_amm_config` function correctly validates these parameters against `FEE_RATE_DENOMINATOR_VALUE` to ensure the rates stay within acceptable bounds. 

> pub const FEE_RATE_DENOMINATOR_VALUE: u64 = 1_000_000;

You should add checking the maximum value for these values on the `create_amm_config` function.

**Comment by SushantChandla** [comment]
Thanks for creating the issue but this is admin level instruction, dont see why admins will ever set values higher than 100%. We can add the check but does not add any value to users of protocol.

**Comment by SushantChandla** [comment]
Ah, just noticed it does have those checks here: https://github.com/GooseFX1/gamma-swap/blob/8143f0328e24a8816987bd7185a59a1e8c94cb9f/programs/gamma/src/lib.rs#L67

Closing, the issue. Thanks for reporting it.
